---
#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 1.1.{build}.0
install:
    - git clone -q --branch=HashtableCheck https://github.com/SSvilen/DscResource.Tests

    - ps: |
          Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
          Invoke-AppveyorInstallTask

          Install-WindowsFeature -Name ADCS-Cert-Authority, RSAT-ADCS
          Restart-Computer -Force
          Start-Sleep -s 10
#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
          Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
          Invoke-AppveyorTestScriptTask `
              -ExcludeTag @() `
              -CodeCoverage `
              -CodeCovIo

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
deploy_script:
    - ps: |
          Invoke-AppveyorAfterTestTask `
              -Type 'Wiki' `
              -ResourceModuleName 'ActiveDirectoryCSDsc'

          Invoke-AppVeyorDeployTask
